name: Release
on: [pull_request]
env:
  PROJECT: "github.com/kelindar/talaria"
  GO111MODULE: "on"

jobs:
  publish:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          go build .
          docker build . --file Dockerfile --tag janqw/talaria:edge
      - name: Push the Docker image
        run: docker push janqw/talaria:edge
